version: "3"

networks:
  backend:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: dan-nginx
    ports:
      - "8084:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - backend
  db:
    image: mysql:5.7.29
    container_name: dan-mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - backend
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dan-php
    volumes:
      - ./src:/var/www/html
    networks:
      - backend

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - backend

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dan-artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    working_dir: /var/www/html
    entrypoint: [ "php", "/var/www/html/artisan" ]
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8085:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - backend


